### ISSUE TITLE
BLE Mesh example

### ISSUE THREAD

**Issue by iot-lorawan** [SiliconLabsSoftware/bluetooth_applications#4]
Hi，
    the bluetooth_applications seam all  BLE not BLE mesh，if we want develop ble product，should we use ble mesh or ble. Does the ble mesh can run in production stage？

**Comment by anhirvon** [comment]
HI,
thank you for your question.
If you are planning to create BT Mesh related product then you have to use BT Mesh related stack technology.

br,
Antti

**Comment by ghost** [comment]
Hi,

Please see the Silicon Labs SDK for latest BT Mesh stack and examples that are suitable for production use.

See https://github.com/SiliconLabs/bluetooth_mesh_stack_features for experimental sample code that is meant as an example only (not production use).

Best regards,
Chris

**Comment by iot-lorawan** [comment]
Hi,
   Thank your for your refer.

Best Regard.
